name: test
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  formatter:
    name: Run CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Implementation
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v4
      - name: Test check
        shell: julia --proj --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
          Pkg.add("Test")
          Pkg.test(;coverage=true)

